stages:
  data_ingestion:
    cmd: python -m src.data.download_dataset
    deps:
      - src/data/download_dataset.py
      - src/utils/logger.py
      - src/utils/paths.py
    params:
      - data_ingestion.url
      - data_ingestion.output_path
    outs:
      - data/raw/reddit_comments.csv

  data_preparation:
    cmd: python -m src.data.make_dataset
    deps:
      - data/raw/reddit_comments.csv
      - src/data/make_dataset.py
      - src/utils/logger.py
      - src/utils/paths.py
    params:
      - data_preparation.test_size
      - data_preparation.random_state
    outs:
      - data/processed/train.parquet
      - data/processed/val.parquet
      - data/processed/test.parquet

  # Transient processing stage for feature comparison (no outs)
  feature_comparison:
    cmd: python -m src.features.tfidf_vs_distilbert
    deps:
      - data/processed/train.parquet
      - data/processed/val.parquet
      - src/features/tfidf_vs_distilbert.py
      - src/utils/logger.py
      - src/features/helpers/feature_utils.py
    params:
      - feature_comparison.mlflow_uri
      - feature_comparison.ngram_ranges
      - feature_comparison.max_features
      - feature_comparison.batch_size
      - feature_comparison.n_estimators
      - feature_comparison.max_depth

  feature_tuning:
    cmd: python -m src.features.tfidf_max_features
    deps:
      - data/processed/train.parquet
      - data/processed/val.parquet
      - src/features/tfidf_max_features.py
      - src/utils/logger.py
      - src/utils/paths.py
      - src/features/helpers/feature_utils.py
    params:
      - feature_tuning.max_features_values
      - feature_tuning.best_ngram_range
      - feature_tuning.n_estimators
      - feature_tuning.max_depth
    outs:
      - reports/figures/tfidf_max_features/

  imbalance_tuning:
    cmd: python -m src.features.imbalance_tuning
    deps:
    - data/processed/train.parquet
    - data/processed/val.parquet
    - src/features/imbalance_tuning.py
    - src/utils/logger.py
    - src/utils/paths.py
    - src/features/helpers/feature_utils.py
    params:
    - imbalance_tuning.imbalance_methods
    - imbalance_tuning.best_max_features
    - imbalance_tuning.best_ngram_range
    - imbalance_tuning.rf_n_estimators
    - imbalance_tuning.rf_max_depth
    outs:
    - reports/figures/imbalance_methods/

  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
      - data/processed/train.parquet
      - data/processed/val.parquet
      - data/processed/test.parquet
      - src/features/feature_engineering.py
      - src/utils/logger.py
      - src/utils/paths.py
      - src/features/helpers/feature_utils.py
    params:
      - feature_engineering.use_distilbert
      - feature_engineering.distilbert_batch_size
      # Reuse best parameters found in tuning stages
      - imbalance_tuning.best_max_features
      - imbalance_tuning.best_ngram_range
    outs:
      - models/features/

  baseline_model:
    cmd: python -m src.models.baseline_logistic
    deps:
      - models/features/X_train.npz
      - models/features/X_val.npz
      - models/features/X_test.npz
      - models/features/y_train.npy
      - models/features/y_val.npy
      - models/features/y_test.npy
      - models/features/label_encoder.pkl
      - src/models/baseline_logistic.py
      - src/models/helpers/data_loader.py
      - src/models/helpers/train_utils.py
      - src/utils/mlflow_config.py
      - src/utils/logger.py
      - src/utils/paths.py
    params:
      - train.logistic_baseline.model_type
      - train.logistic_baseline.class_weight
      - train.logistic_baseline.solver
      - train.logistic_baseline.max_iter
    outs:
      - models/baseline/logistic_baseline.pkl
    metrics:
      - models/baseline/baseline_metrics.json

  hyperparameter_tuning_lightgbm:
    cmd: python -m src.models.hyperparameter_tuning --model lightgbm
    deps:
      - src/models/hyperparameter_tuning.py
      - src/models/helpers/data_loader.py
      - src/models/helpers/train_utils.py
      - src/utils/mlflow_config.py
      - src/utils/logger.py
      - models/features/X_train.npz
      - models/features/X_val.npz
      - models/features/y_train.npy
      - models/features/y_val.npy
    params:
      - train.hyperparameter_tuning.lightgbm
    outs:
      - models/advanced/lightgbm_model.pkl
      - models/advanced/lightgbm_best_hyperparams.pkl
    metrics:
      - models/advanced/lightgbm_metrics.json

  hyperparameter_tuning_xgboost:
    cmd: python -m src.models.hyperparameter_tuning --model xgboost
    deps:
      - src/models/hyperparameter_tuning.py
      - src/models/helpers/data_loader.py
      - src/models/helpers/train_utils.py
      - src/utils/mlflow_config.py
      - src/utils/logger.py
      - models/features/X_train.npz
      - models/features/X_val.npz
      - models/features/y_train.npy
      - models/features/y_val.npy
    params:
      - train.hyperparameter_tuning.xgboost
    outs:
      - models/advanced/xgboost_model.pkl
      - models/advanced/xgboost_best_hyperparams.pkl
    metrics:
      - models/advanced/xgboost_metrics.json

  train_distilbert:
    cmd: python -m src.models.distilbert_training
    deps:
      - src/models/distilbert_training.py
      - src/models/helpers/data_loader.py
      - src/models/helpers/train_utils.py
      - src/utils/mlflow_config.py
      - src/utils/paths.py
      - src/utils/logger.py
      - data/processed/train.parquet
      - data/processed/val.parquet
    outs:
      - models/advanced/distilbert_model.pkl
      - models/advanced/distilbert_results
    params:
      - train.distilbert.enable
      - train.distilbert.n_trials
      - train.distilbert.batch_size
      - train.distilbert.lr
      - train.distilbert.weight_decay
    metrics:
      - models/advanced/distilbert_metrics.json

  model_evaluation:
    cmd: python -m src.models.model_evaluation
    deps:
      - src/models/model_evaluation.py
      - src/utils/mlflow_config.py
      - src/utils/logger.py
      - src/utils/paths.py
      - src/models/helpers/data_loader.py
      - src/models/helpers/train_utils.py
      # The model artifacts produced by the training stages
      - models/advanced/lightgbm_model.pkl
      - models/advanced/xgboost_model.pkl
      # Baseline model artifact
      - models/baseline/logistic_baseline.pkl
      # DistilBERT model artifact
      - models/advanced/distilbert_model.pkl
      - models/advanced/distilbert_results
      # The features for the test set
      - models/features/X_test.npz
      - models/features/y_test.npy
      - models/features/label_encoder.pkl
    outs:
      # Output file for the next stage (registration)
      - models/advanced/evaluation/best_model_run_info.json
      # Corrected paths to match script output (reports/figures/evaluation/)
      - models/advanced/evaluation/lightgbm_test_metrics.json
      - models/advanced/evaluation/xgboost_test_metrics.json
      - models/advanced/evaluation/logistic_baseline_test_metrics.json
      # - models/advanced/evaluation/distilbert_test_metrics.json
      # Visualizations
      - reports/figures/evaluation/lightgbm_confusion_matrix.png  
      - reports/figures/evaluation/xgboost_confusion_matrix.png   
      - reports/figures/evaluation/comparative_roc_curve.png     
    params:
      - model_evaluation.models

  register_model:
    cmd: python -m src.models.register_model
    deps:
      - src/models/register_model.py
      - src/utils/mlflow_config.py
      - src/utils/logger.py
      - src/utils/paths.py
      # Depends on the champion file and metrics from the evaluation stage
      - models/advanced/evaluation/best_model_run_info.json
      - models/advanced/evaluation/lightgbm_test_metrics.json
      - models/advanced/evaluation/xgboost_test_metrics.json
      - models/advanced/evaluation/logistic_baseline_test_metrics.json
    params:
      - register.f1_threshold
    



