name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      run: pip install uv
    - name: Set up virtual environment
      run: uv venv && uv pip install -r requirements.txt
    - name: Run linting
      run: uv pip install flake8 && flake8 src/
    - name: Run tests
      run: uv pip install pytest && pytest src/