"""
Component for validating and registering champion models into MLflow.

This module provides the worker component responsible for dynamically reading
the champion model information generated by the evaluation stage, ensuring it meets
the F1 threshold, and pushing it to the MLflow Model Registry as 'Production'.
"""

import json

import mlflow
from mlflow.tracking import MlflowClient
from packaging import version

from src.constants import EVAL_DIR
from src.entity.config_entity import RegisterConfig
from src.utils.logger import get_logger

logger = get_logger(__name__, headline="register_model_component")


class ModelRegistration:
    """
    Component acting as the gatekeeper for the MLflow Model Registry.

    Attributes:
        config (RegisterConfig): Registration configuration containing the minimum F1 threshold.
    """

    def __init__(self, config: RegisterConfig):
        """
        Initialize the ModelRegistration component.

        Args:
            config (RegisterConfig): Configuration object containing parameters.
        """
        self.config = config

    def load_champion_model_data(self):
        """
        Load the metadata of the champion model chosen during the evaluation stage.

        Reads the `best_model_run_info.json` and its respective test metrics.

        Returns:
            tuple: A tuple containing (model_name, run_id, f1_score).

        Raises:
            FileNotFoundError: If the champion JSON tracking files are missing.
            KeyError: If the macro F1 score cannot be found in the parsed payload.
        """
        try:
            info_path = EVAL_DIR / "best_model_run_info.json"
            if not info_path.exists():
                raise FileNotFoundError(f"Champion info file not found at {info_path}")

            with open(info_path) as f:
                info = json.load(f)

            model_name = info["model_name"]
            run_id = info["run_id"]

            metric_path = EVAL_DIR / f"{model_name}_test_metrics.json"
            if not metric_path.exists():
                raise FileNotFoundError(f"Champion's metric file not found at {metric_path}")

            with open(metric_path) as f:
                metrics = json.load(f)

            f1_score = metrics.get("test_macro_f1")
            if f1_score is None:
                raise KeyError(f"'test_macro_f1' not found in {metric_path}")

            logger.info(
                f"🏆 Champion identified: {model_name.upper()} (Run ID: {run_id}) | Test Macro F1: {f1_score:.4f} "
            )
            return model_name, run_id, f1_score

        except Exception as e:
            logger.error(f"Error loading champion model data: {e}")
            raise

    def register_best_model(self, model_name: str, run_id: str, f1: float):
        """
        Evaluate if the champion model passes the score requirement and register it to MLflow.

        This method accounts for MLflow versions (pre/post v2.9.0) when tagging models
        as 'Production'.

        Args:
            model_name (str): The name identifier of the model.
            run_id (str): The MLflow run ID containing the trained artifact.
            f1 (float): The validated test F1 score to compare against the threshold.
        """
        client = MlflowClient()
        logger.info("🚀 Starting model registration process... 🚀")
        model_registry_name = f"youtube_sentiment_{model_name}"

        if f1 < self.config.f1_threshold:
            logger.warning(
                f"❌ Model performance below threshold (F1={f1:.4f} < {self.config.f1_threshold:.2f}). "
                f"Skipping registration for model '{model_registry_name}'."
            )
            return

        logger.info(f"Model performance meets threshold (F1={f1:.4f} >= {self.config.f1_threshold:.2f}).")

        try:
            logger.info(f"Registering model '{model_registry_name}' from run {run_id}")
            model_uri = f"runs:/{run_id}/model"
            model_version = mlflow.register_model(
                model_uri=model_uri,
                name=model_registry_name,
            )
            logger.info(f"✅ Successfully registered model '{model_registry_name}' version {model_version.version} ✅")

        except Exception as e:
            logger.error(f"❌ Failed to register model '{model_registry_name}': {e}")
            raise

        mlflow_version = version.parse(mlflow.__version__)
        supports_stages = mlflow_version < version.parse("2.9.0")

        try:
            if supports_stages:
                client.transition_model_version_stage(
                    name=model_registry_name,
                    version=model_version.version,
                    stage="Production",
                    archive_existing_versions=True,
                )
                logger.info(f"🟢 Model version {model_version.version} transitioned to 'Production' stage.")
            else:
                client.set_model_version_tag(
                    name=model_registry_name,
                    version=model_version.version,
                    key="deployment_stage",
                    value="Production",
                )
                logger.info(
                    f"🟢 MLflow ≥ 2.9 detected — set tag 'deployment_stage=Production' "
                    f"for model version {model_version.version}."
                )

        except Exception as e:
            logger.warning(
                f"⚠️ Stage/Tag assignment failed for model '{model_registry_name}' (v{model_version.version}): {e}"
            )
            logger.info("Continuing without stage assignment (likely unsupported in local MLflow file store).")

        logger.info(
            f"🧾 Registration Summary → Model: {model_registry_name} | Version: {model_version.version} | F1: {f1:.4f}"
        )
        logger.info("🏁 Model registration workflow completed successfully. 🏁")

    def run_registration(self):
        """
        Orchestrate the MLflow registration workflow.

        Retrieves the champion details and pushes it to MLflow if threshold validation succeeds.
        """
        try:
            model_name, run_id, f1 = self.load_champion_model_data()
            self.register_best_model(model_name, run_id, f1)
        except Exception as e:
            logger.error(f"❌ Model registration failed: {e}")
            raise
